version: "3.7"

services:
  students-mysql-service:
    image: mysql:latest
    networks:
      - spring-boot-mysql-network
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=students
      - MYSQL_PASSWORD=students
      - MYSQL_USER=students
  students-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9091:8080
    networks:
      - spring-boot-mysql-network
    restart: always
    depends_on:
      - students-mysql-service
networks:
  spring-boot-mysql-network:
    driver: bridge