server:
  port: 8080
spring:
  application:
    name: ms-students
  datasource:
#    url: jdbc:mysql://students-mysql-service:3306/students?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/students?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: students
    password: students
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true